### PR TITLE
chore: set up semantic release

### PR DESCRIPTION
**Pull request by rosshadden**

### CODE REVIEW

**Review by spencern — CHANGES_REQUESTED** [review]
This looks good. One last bit for semantic release is to add a CircleCI config that includes the reaction-publish-semantic-release context and runs the build/deploy job

See: https://github.com/reactioncommerce/plugin-simple-authorization/blob/trunk/.circleci/config.yml#L71 for an example

**Comment by kieckhafer** [comment]
I think this is set up correctly, pending changes based on @spencern's comment.

**Review by spencern — DISMISSED** [review]
Looks good w/ a few comments:
1. the deploy CI workflow is filtering to run exclusively on `trunk` - you've already updated the branch here, so that should be good to go.
2. a `chore` commit won't trigger a build, only `feat` or `fix`. So when this merges, I don't think it will publish.

**Review by spencern — APPROVED** [review]
LGTM 👍

**Review by kieckhafer — APPROVED** [review]
👍

**Pull request merged**
